---
- name: Laptop setup
  hosts: laptop
  become: True
  become_user: root
  vars_prompt:
    - name: "ansible_sudo_pass"
      prompt: "Sudo password"
      private: yes
  roles:
#    - { role: user, username: alexander }
  tasks:
    - include: tasks/fedora-common.yml
    - include: tasks/i3.yml
    - include: tasks/desktop.yml
